### PR TITLE
Updates to support Crystal v0.25.1

### PR DESCRIPTION
**Pull request by chris-huxtable**
- Updates minitest to v0.4.0
- Adds default `Time::Location` as UTC

### CODE REVIEW

**Comment by wmoxam** [comment]
Hey, thanks for this! I'll check it out

**Comment by chris-huxtable** [comment]
I need to change this to `Time::Location.local`. I assumed it defaulted to UTC and was wrong. 
- [Liquid date](https://shopify.github.io/liquid/filters/date/)
- [ruby `Time.parse()`](https://ruby-doc.org/stdlib-2.5.1/libdoc/time/rdoc/Time.html#method-c-parse)

**Comment by chris-huxtable** [comment]
Should be fixed now.

**Review by wmoxam — APPROVED** [review]
Thanks!

**Pull request merged**
